env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-param-reassign: ["error", { "props": false }]
}
